require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe AnonymousSlidesController do

  # This should return the minimal set of attributes required to create a valid
  # AnonymousSlide. As you add validations to AnonymousSlide, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { {  } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # AnonymousSlidesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all anonymous_slides as @anonymous_slides" do
      anonymous_slide = AnonymousSlide.create! valid_attributes
      get :index, {}, valid_session
      assigns(:anonymous_slides).should eq([anonymous_slide])
    end
  end

  describe "GET show" do
    it "assigns the requested anonymous_slide as @anonymous_slide" do
      anonymous_slide = AnonymousSlide.create! valid_attributes
      get :show, {:id => anonymous_slide.to_param}, valid_session
      assigns(:anonymous_slide).should eq(anonymous_slide)
    end
  end

  describe "GET new" do
    it "assigns a new anonymous_slide as @anonymous_slide" do
      get :new, {}, valid_session
      assigns(:anonymous_slide).should be_a_new(AnonymousSlide)
    end
  end

  describe "GET edit" do
    it "assigns the requested anonymous_slide as @anonymous_slide" do
      anonymous_slide = AnonymousSlide.create! valid_attributes
      get :edit, {:id => anonymous_slide.to_param}, valid_session
      assigns(:anonymous_slide).should eq(anonymous_slide)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new AnonymousSlide" do
        expect {
          post :create, {:anonymous_slide => valid_attributes}, valid_session
        }.to change(AnonymousSlide, :count).by(1)
      end

      it "assigns a newly created anonymous_slide as @anonymous_slide" do
        post :create, {:anonymous_slide => valid_attributes}, valid_session
        assigns(:anonymous_slide).should be_a(AnonymousSlide)
        assigns(:anonymous_slide).should be_persisted
      end

      it "redirects to the created anonymous_slide" do
        post :create, {:anonymous_slide => valid_attributes}, valid_session
        response.should redirect_to(AnonymousSlide.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved anonymous_slide as @anonymous_slide" do
        # Trigger the behavior that occurs when invalid params are submitted
        AnonymousSlide.any_instance.stub(:save).and_return(false)
        post :create, {:anonymous_slide => {  }}, valid_session
        assigns(:anonymous_slide).should be_a_new(AnonymousSlide)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        AnonymousSlide.any_instance.stub(:save).and_return(false)
        post :create, {:anonymous_slide => {  }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested anonymous_slide" do
        anonymous_slide = AnonymousSlide.create! valid_attributes
        # Assuming there are no other anonymous_slides in the database, this
        # specifies that the AnonymousSlide created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        AnonymousSlide.any_instance.should_receive(:update).with({ "these" => "params" })
        put :update, {:id => anonymous_slide.to_param, :anonymous_slide => { "these" => "params" }}, valid_session
      end

      it "assigns the requested anonymous_slide as @anonymous_slide" do
        anonymous_slide = AnonymousSlide.create! valid_attributes
        put :update, {:id => anonymous_slide.to_param, :anonymous_slide => valid_attributes}, valid_session
        assigns(:anonymous_slide).should eq(anonymous_slide)
      end

      it "redirects to the anonymous_slide" do
        anonymous_slide = AnonymousSlide.create! valid_attributes
        put :update, {:id => anonymous_slide.to_param, :anonymous_slide => valid_attributes}, valid_session
        response.should redirect_to(anonymous_slide)
      end
    end

    describe "with invalid params" do
      it "assigns the anonymous_slide as @anonymous_slide" do
        anonymous_slide = AnonymousSlide.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        AnonymousSlide.any_instance.stub(:save).and_return(false)
        put :update, {:id => anonymous_slide.to_param, :anonymous_slide => {  }}, valid_session
        assigns(:anonymous_slide).should eq(anonymous_slide)
      end

      it "re-renders the 'edit' template" do
        anonymous_slide = AnonymousSlide.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        AnonymousSlide.any_instance.stub(:save).and_return(false)
        put :update, {:id => anonymous_slide.to_param, :anonymous_slide => {  }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested anonymous_slide" do
      anonymous_slide = AnonymousSlide.create! valid_attributes
      expect {
        delete :destroy, {:id => anonymous_slide.to_param}, valid_session
      }.to change(AnonymousSlide, :count).by(-1)
    end

    it "redirects to the anonymous_slides list" do
      anonymous_slide = AnonymousSlide.create! valid_attributes
      delete :destroy, {:id => anonymous_slide.to_param}, valid_session
      response.should redirect_to(anonymous_slides_url)
    end
  end

end
